# RTOFS systems: "v2p4" or "v2p5" or "v2p5_bad" or "v2p5_nco"
system_name: "v2p5_nco" 

# Path to grid file.
grid_file: /lfs/h2/emc/couple/noscrub/santha.akella/data_files/v2.5/topog/regional.grid.a

# Path to where archive files are staged.
# Following path is expected to have directories: "yyyymmdd/"
input_path: /lfs/h2/emc/ptmp/santha.akella/data/rtofs/v2p5_nco/

start_date: 2025-05-30
end_date: 2025-06-06

# Which archives to process? Must be one at a time: "n00".
arch_type: rtofs_glo.t00z.n00.archs.

# Names of variables, must match what is in the archive [b] file.
arch_variables: ['temp', 'salin', 'srfhgt', 'u-vel', 'v-vel']

# Extra variables that are derived from above.
do_extraVars: True # True/False
extra_variables: ['curr']

# Output path where output: (nc) files, plots, etc, are to be saved.
output_path: /lfs/h2/emc/ptmp/santha.akella/data/arch2nc/v2p5_nco
