      REAL FUNCTION JGUF04(SCALE,SUMSQ,BIG)
C     MARK 8 RELEASE. NAG COPYRIGHT 1979.
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C     MARK 13 REVISED. USE OF MARK 12 X02 FUNCTIONS (APR 1988).
C     WRITTEN BY S. HAMMARLING, MIDDLESEX POLYTECHNIC (TWONRM)
C
C     JGUF04 RETURNS THE VALUE
C
C     JGUF04 = SCALE*SQRT(SUMSQ) .
C
C     SCALE IS ASSUMED TO BE NON-NEGATIVE AND SUMSQ IS ASSUMED
C     TO BE AT LEAST UNITY.
C
C     BIG MUST BE GIVEN BY
C
C     BIG = 1.0/X02AME ,
C
C     WHERE X02AME IS THE SMALL REAL VALUE RETURNED FROM
C     ROUTINE X02AME.
C
C     JGUF04 IS USED IN CONJUNCTION WITH JGTF04 BY VARIOUS
C     EUCLIDEAN NORM ROUTINES.
C
C     .. Scalar Arguments ..
      REAL                 BIG, SCALE, SUMSQ
C     .. Intrinsic Functions ..
      INTRINSIC            SQRT
C     .. Executable Statements ..
      IF (SCALE.GE.BIG/SUMSQ) GO TO 20
      JGUF04 = SCALE*SQRT(SUMSQ)
      RETURN
C
   20 JGUF04 = BIG
      RETURN
      END
