      LOGICAL FUNCTION JGXF04(A,B,SMALL)
C     MARK 8 RELEASE. NAG COPYRIGHT 1979.
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C     MARK 13 REVISED. USE OF MARK 12 X02 FUNCTIONS (APR 1988).
C     WRITTEN BY S. HAMMARLING, MIDDLESEX POLYTECHNIC (OVFLOW)
C
C     JGXF04 WILL BE .TRUE. IF THE DIVISION A/B IS LIKELY TO
C     RESULT IN OVERFLOW. JGXF04 WILL BE .FALSE. IF A/B CAN BE
C     COMPUTED WITHOUT OVERFLOW.
C
C     SMALL MUST BE THE SMALL POSITIVE REAL NUMBER RETURNED
C     FROM ROUTINE X02AME.
C
C     .. Scalar Arguments ..
      REAL                    A, B, SMALL
C     .. Intrinsic Functions ..
      INTRINSIC               ABS
C     .. Executable Statements ..
      IF (B.EQ.0.0) GO TO 20
      JGXF04 = .FALSE.
      IF (ABS(B).GE.1.0) RETURN
      IF (ABS(A).LE.ABS(B)/SMALL) RETURN
   20 JGXF04 = .TRUE.
      RETURN
      END
