      REAL FUNCTION WDZF02(N,A,NRA,WORK)
C     MARK 8 RELEASE. NAG COPYRIGHT 1979.
C     MARK 11.5(F77) REVISED. (SEPT 1985.)
C     MARK 13 REVISED. USE OF MARK 12 X02 FUNCTIONS (APR 1988).
C     WRITTEN BY S. HAMMARLING, MIDDLESEX POLYTECHNIC (CONDTN)
C
C     WDZF02 RETURNS THE CONDITION NUMBER OF THE N*N UPPER
C     TRIANGULAR MATRIX A GIVEN BY
C
C     WDZF02 = NORM(A)*NORM(A**(-1)) ,
C
C     WHERE NORM DENOTES THE EUCLIDEAN NORM.
C
C     NRA MUST BE THE ACTUAL ROW DIMENSION OF A AS DECLARED IN
C     THE CALLING PROGRAM AND MUST BE AT LEAST N.
C
C     WORK IS A WORK ARRAY WHOSE LENGTH MUST BE AT LEAST N.
C
C     ONLY THE UPPER TRIANGULAR PART OF A IS REFERENCED.
C
C     IF THE CONDITION NUMBER WOULD OVERFLOW THEN WDZF02 IS
C     RETURNED AS 1.0/SMALL, WHERE SMALL IS THE SMALL POSITIVE
C     REAL NUMBER RETURNED FROM ROUTINE X02AME.
C
C     .. Scalar Arguments ..
      INTEGER              N, NRA
C     .. Array Arguments ..
      REAL                 A(NRA,N), WORK(N)
C     .. Local Scalars ..
      REAL                 AINVNM, ANORM, BIG, SMALL
C     .. External Functions ..
      REAL                 JGRF04, JGSF04, X02AME
      EXTERNAL             JGRF04, JGSF04, X02AME
C     .. Executable Statements ..
      SMALL = X02AME()
      BIG = 1.0/SMALL
C
      WDZF02 = BIG
C
      AINVNM = JGRF04(N,A,NRA,WORK)
C
      IF (AINVNM.EQ.BIG) RETURN
C
      ANORM = JGSF04(N,A,NRA)
C
      IF (AINVNM.LT.1.0) GO TO 20
      IF (ANORM.GE.BIG/AINVNM) RETURN
C
   20 WDZF02 = AINVNM*ANORM
C
      RETURN
      END
